### PR TITLE
Ionic 4 Support

### PR DESCRIPTION
**Pull request by danielsogl**

### CODE REVIEW

**Comment by mcking49** [comment]
Would be awesome to get this merged in for Ionic 4 support.

**Comment by sneas** [comment]
@danielsogl, thank you for the PR.
@mcking49, while Ionic 4 is still in beta I would like this PR to be released under @next tag. Unfortunately I have limited access to computer until Friday. Will take care of this as soon as possible.

**Comment by sneas** [comment]
The release strategy considering release tags controlled by semantic-release is not entirely clear to me yet. Will dig into it.

**Comment by mcking49** [comment]
Cool, no hurry. Thanks for the update! :)

**Comment by danielsogl** [comment]
Thanks for the update

**Comment by sneas** [comment]
Hi @danielsogl, unit tests are failing with the message `Cannot find module '@ionic/angular' from 'native-http-fallback.spec.ts'` do you know why could it be?

**Pull request merged**
