### PR TITLE
feat: Ionic 4.0 and Angular 7 support

### PR DESCRIPTION
**Pull request by danielsogl**

### CODE REVIEW

**Comment by danielsogl** [comment]
We should also upgrade to the HttpClient.

**Comment by sneas** [comment]
Thank you for the PR, @danielsogl. The "upgrade to the HttpClient" is not very clear to me. Could you please explain?

**Comment by danielsogl** [comment]
Actually the lib is using the deprecated `HttpModule`. This API is deprecated since Angular 4.0.
The new package is called `HttpClientModule` and can imported from `@angular/common/http`.
This is why the lib should be refactored to use the new module.

**Comment by sneas** [comment]
Ah I see it. I will take care of this.

**Comment by sneas** [comment]
Sorry, overlooked the `angular/http` usage. The usage of `angular/http` is described here https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md

There is no need in refactoring. We can delete [src/http](https://github.com/sneas/ionic-native-http-connection-backend/tree/master/src/http) folder and [DEPRECATED.md ](https://github.com/sneas/ionic-native-http-connection-backend/blob/master/DEPRECATED.md) any time.

**Pull request merged**
